import { StyleSheet, Dimensions} from "react-native";

const dibujar=StyleSheet.create({
    Container:{
      width:'100%',
      height:'100%',
      padding:20,
      backgroundColor:'#ffd9cc'
    },
    Title:{
      fontSize:25,
      color:'#8c66ff',
    },
    TextInput:{
      borderColor:'#d966ff',
      borderWidth:1,
      borderRadius:15,
      width:Dimensions.get("screen").width*0.6,
      paddingLeft:10
    },
    textt:{
      fontSize:15,
      color:'black',
    },
    wtext:{
      fontSize:15,
      color:'black',
    },
    InputContainer:{
      marginTop:30,
      flexDirection:"row",
      justifyContent:"space-between"
    },
    Buttonn:{
      width:Dimensions.get("screen").width*0.2,
      backgroundColor:'#d966ff',
      justifyContent:'center',
      alignItems:'center',
      borderRadius:15
    },
    taskcontainer:{
      paddingVertical:25,
      borderBottomColor:'#6666ff',
      borderBottomWidth:5,
      flexDirection:'row',
      justifyContent:'space-between',
    },
    textodone:{
      fontSize:16,
      color:"red",
      textDecorationLine:"line-through"
    },
    removebutton:{
      backgroundColor:'#ff6666',
      justifyContent:'center',
      alignContent:'center',
      paddingHorizontal:15,
      borderRadius:15
    }
  })
  export default dibujar